"""add workday hours to calendar profile

Revision ID: 117e101726ca
Revises: bf00d9eb6971
Create Date: 2026-03-31 12:02:46.612130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "117e101726ca"
down_revision: Union[str, None] = "bf00d9eb6971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_profiles",
        sa.Column(
            "workday_start_hour", sa.Integer(), nullable=False, server_default="9"
        ),
    )
    op.add_column(
        "calendar_profiles",
        sa.Column(
            "workday_end_hour", sa.Integer(), nullable=False, server_default="17"
        ),
    )
    op.alter_column("calendar_profiles", "workday_start_hour", server_default=None)
    op.alter_column("calendar_profiles", "workday_end_hour", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendar_profiles", "workday_end_hour")
    op.drop_column("calendar_profiles", "workday_start_hour")
    # ### end Alembic commands ###
