"""initial models 2

Revision ID: 530db94a99eb
Revises:
Create Date: 2026-03-10 13:24:08.178771

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "530db94a99eb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
