"""add User-Calenadar relationship

Revision ID: 7128861b7fe5
Revises: 72eb607b5603
Create Date: 2026-03-11 23:11:27.287729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7128861b7fe5"
down_revision: Union[str, None] = "72eb607b5603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calendars", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "calendars", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "calendars", type_="foreignkey")
    op.drop_column("calendars", "owner_id")
    # ### end Alembic commands ###
