"""remove profiles from user

Revision ID: 9a20c641b777
Revises: 7128861b7fe5
Create Date: 2026-03-11 23:15:13.538185

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9a20c641b777"
down_revision: Union[str, None] = "7128861b7fe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
