"""fix wrong back population setting on calendar

Revision ID: da330939ac10
Revises: 3ed4f615a293
Create Date: 2026-03-11 23:17:56.477960

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "da330939ac10"
down_revision: Union[str, None] = "3ed4f615a293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
