/* tslint:disable */
/* eslint-disable */
/**
 * Chronicle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

export interface Action {
  id: number;
  rule_id: number;
  name: string;
  arguments: object;
}
export interface CalendarCreate {
  type: string;
  url: string;
  username?: string | null;
  password?: string | null;
}
export interface CalendarRead {
  id: string;
  type: string;
  url: string;
  username: string | null;
  password: string | null;
}
export interface Condition {
  id: number;
  rule_id: number;
  field: string;
  operator: string;
  value: string;
}
export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}
export interface LocationInner {}
export interface LoginRequest {
  email: string;
  password: string;
}
export interface ProfileCreate {
  name: string;
  main_calendar_id: string;
}
export interface ProfileReadFull {
  id: string;
  name: string;
  main_calendar_id: string | null;
  main_calendar: CalendarRead | null;
  rules?: Array<Rule>;
}
export interface ProfileReadShort {
  id: string;
  name: string;
  main_calendar_id: string | null;
}
export interface RegisterRequest {
  email: string;
  password: string;
}
export interface Rule {
  id: number;
  source_id: string;
  enabled: boolean;
  name: string;
  conditions?: Array<Condition>;
  actions?: Array<Action>;
}
export interface SourceCreate {
  calendar_id: string;
}
export interface SourceRead {
  id: string;
  calendar_id: string;
  calendar: CalendarRead;
}
export interface TokenResponse {
  access_token: string;
  token_type?: string;
}
export interface ValidationError {
  loc: Array<LocationInner>;
  msg: string;
  type: string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Login
     * @param {LoginRequest} loginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginApiAuthLoginPost: async (
      loginRequest: LoginRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'loginRequest' is not null or undefined
      assertParamExists("loginApiAuthLoginPost", "loginRequest", loginRequest);
      const localVarPath = `/api/auth/login`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        loginRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logoutApiAuthLogoutPost: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/logout`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Me
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    meApiAuthMeGet: async (
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Register
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerApiAuthRegisterPost: async (
      registerRequest: RegisterRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'registerRequest' is not null or undefined
      assertParamExists(
        "registerApiAuthRegisterPost",
        "registerRequest",
        registerRequest,
      );
      const localVarPath = `/api/auth/register`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        registerRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Login
     * @param {LoginRequest} loginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async loginApiAuthLoginPost(
      loginRequest: LoginRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.loginApiAuthLoginPost(
          loginRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.loginApiAuthLoginPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async logoutApiAuthLogoutPost(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.logoutApiAuthLogoutPost(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.logoutApiAuthLogoutPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Me
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async meApiAuthMeGet(
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.meApiAuthMeGet(
        authorization,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.meApiAuthMeGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Register
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async registerApiAuthRegisterPost(
      registerRequest: RegisterRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.registerApiAuthRegisterPost(
          registerRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.registerApiAuthRegisterPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AuthApiFp(configuration);
  return {
    /**
     *
     * @summary Login
     * @param {LoginRequest} loginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginApiAuthLoginPost(
      loginRequest: LoginRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TokenResponse> {
      return localVarFp
        .loginApiAuthLoginPost(loginRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logoutApiAuthLogoutPost(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .logoutApiAuthLogoutPost(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Me
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    meApiAuthMeGet(
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .meApiAuthMeGet(authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Register
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerApiAuthRegisterPost(
      registerRequest: RegisterRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TokenResponse> {
      return localVarFp
        .registerApiAuthRegisterPost(registerRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
  /**
   *
   * @summary Login
   * @param {LoginRequest} loginRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public loginApiAuthLoginPost(
    loginRequest: LoginRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .loginApiAuthLoginPost(loginRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Logout
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public logoutApiAuthLogoutPost(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .logoutApiAuthLogoutPost(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Me
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public meApiAuthMeGet(
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .meApiAuthMeGet(authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Register
   * @param {RegisterRequest} registerRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public registerApiAuthRegisterPost(
    registerRequest: RegisterRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return AuthApiFp(this.configuration)
      .registerApiAuthRegisterPost(registerRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * CalendarApi - axios parameter creator
 */
export const CalendarApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Create a new calendar for the current user.
     * @summary Create Calendar
     * @param {CalendarCreate} calendarCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCalendarApiCalendarPost: async (
      calendarCreate: CalendarCreate,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarCreate' is not null or undefined
      assertParamExists(
        "createCalendarApiCalendarPost",
        "calendarCreate",
        calendarCreate,
      );
      const localVarPath = `/api/calendar`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        calendarCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete a calendar by ID.
     * @summary Delete Calendar
     * @param {string} calendarId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCalendarApiCalendarCalendarIdDelete: async (
      calendarId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarId' is not null or undefined
      assertParamExists(
        "deleteCalendarApiCalendarCalendarIdDelete",
        "calendarId",
        calendarId,
      );
      const localVarPath = `/api/calendar/{calendar_id}`.replace(
        `{${"calendar_id"}}`,
        encodeURIComponent(String(calendarId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieve a calendar by ID.
     * @summary Get Calendar
     * @param {string} calendarId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCalendarApiCalendarCalendarIdGet: async (
      calendarId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarId' is not null or undefined
      assertParamExists(
        "getCalendarApiCalendarCalendarIdGet",
        "calendarId",
        calendarId,
      );
      const localVarPath = `/api/calendar/{calendar_id}`.replace(
        `{${"calendar_id"}}`,
        encodeURIComponent(String(calendarId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieve all calendars for the current user.
     * @summary List Calendars
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCalendarsApiCalendarGet: async (
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/calendar`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Update a calendar by ID.
     * @summary Update Calendar
     * @param {string} calendarId
     * @param {CalendarCreate} calendarCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCalendarApiCalendarCalendarIdPut: async (
      calendarId: string,
      calendarCreate: CalendarCreate,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarId' is not null or undefined
      assertParamExists(
        "updateCalendarApiCalendarCalendarIdPut",
        "calendarId",
        calendarId,
      );
      // verify required parameter 'calendarCreate' is not null or undefined
      assertParamExists(
        "updateCalendarApiCalendarCalendarIdPut",
        "calendarCreate",
        calendarCreate,
      );
      const localVarPath = `/api/calendar/{calendar_id}`.replace(
        `{${"calendar_id"}}`,
        encodeURIComponent(String(calendarId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        calendarCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CalendarApi - functional programming interface
 */
export const CalendarApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CalendarApiAxiosParamCreator(configuration);
  return {
    /**
     * Create a new calendar for the current user.
     * @summary Create Calendar
     * @param {CalendarCreate} calendarCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createCalendarApiCalendarPost(
      calendarCreate: CalendarCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalendarRead>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createCalendarApiCalendarPost(
          calendarCreate,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.createCalendarApiCalendarPost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Delete a calendar by ID.
     * @summary Delete Calendar
     * @param {string} calendarId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteCalendarApiCalendarCalendarIdDelete(
      calendarId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteCalendarApiCalendarCalendarIdDelete(
          calendarId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarApi.deleteCalendarApiCalendarCalendarIdDelete"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieve a calendar by ID.
     * @summary Get Calendar
     * @param {string} calendarId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCalendarApiCalendarCalendarIdGet(
      calendarId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalendarRead>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getCalendarApiCalendarCalendarIdGet(
          calendarId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.getCalendarApiCalendarCalendarIdGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieve all calendars for the current user.
     * @summary List Calendars
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listCalendarsApiCalendarGet(
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<CalendarRead>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listCalendarsApiCalendarGet(
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.listCalendarsApiCalendarGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Update a calendar by ID.
     * @summary Update Calendar
     * @param {string} calendarId
     * @param {CalendarCreate} calendarCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateCalendarApiCalendarCalendarIdPut(
      calendarId: string,
      calendarCreate: CalendarCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalendarRead>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateCalendarApiCalendarCalendarIdPut(
          calendarId,
          calendarCreate,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarApi.updateCalendarApiCalendarCalendarIdPut"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CalendarApi - factory interface
 */
export const CalendarApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CalendarApiFp(configuration);
  return {
    /**
     * Create a new calendar for the current user.
     * @summary Create Calendar
     * @param {CalendarCreate} calendarCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCalendarApiCalendarPost(
      calendarCreate: CalendarCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CalendarRead> {
      return localVarFp
        .createCalendarApiCalendarPost(calendarCreate, authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete a calendar by ID.
     * @summary Delete Calendar
     * @param {string} calendarId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCalendarApiCalendarCalendarIdDelete(
      calendarId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteCalendarApiCalendarCalendarIdDelete(
          calendarId,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieve a calendar by ID.
     * @summary Get Calendar
     * @param {string} calendarId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCalendarApiCalendarCalendarIdGet(
      calendarId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CalendarRead> {
      return localVarFp
        .getCalendarApiCalendarCalendarIdGet(calendarId, authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieve all calendars for the current user.
     * @summary List Calendars
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCalendarsApiCalendarGet(
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<CalendarRead>> {
      return localVarFp
        .listCalendarsApiCalendarGet(authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Update a calendar by ID.
     * @summary Update Calendar
     * @param {string} calendarId
     * @param {CalendarCreate} calendarCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCalendarApiCalendarCalendarIdPut(
      calendarId: string,
      calendarCreate: CalendarCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CalendarRead> {
      return localVarFp
        .updateCalendarApiCalendarCalendarIdPut(
          calendarId,
          calendarCreate,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CalendarApi - object-oriented interface
 */
export class CalendarApi extends BaseAPI {
  /**
   * Create a new calendar for the current user.
   * @summary Create Calendar
   * @param {CalendarCreate} calendarCreate
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createCalendarApiCalendarPost(
    calendarCreate: CalendarCreate,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarApiFp(this.configuration)
      .createCalendarApiCalendarPost(calendarCreate, authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete a calendar by ID.
   * @summary Delete Calendar
   * @param {string} calendarId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteCalendarApiCalendarCalendarIdDelete(
    calendarId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarApiFp(this.configuration)
      .deleteCalendarApiCalendarCalendarIdDelete(
        calendarId,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieve a calendar by ID.
   * @summary Get Calendar
   * @param {string} calendarId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getCalendarApiCalendarCalendarIdGet(
    calendarId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarApiFp(this.configuration)
      .getCalendarApiCalendarCalendarIdGet(calendarId, authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieve all calendars for the current user.
   * @summary List Calendars
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listCalendarsApiCalendarGet(
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarApiFp(this.configuration)
      .listCalendarsApiCalendarGet(authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Update a calendar by ID.
   * @summary Update Calendar
   * @param {string} calendarId
   * @param {CalendarCreate} calendarCreate
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateCalendarApiCalendarCalendarIdPut(
    calendarId: string,
    calendarCreate: CalendarCreate,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarApiFp(this.configuration)
      .updateCalendarApiCalendarCalendarIdPut(
        calendarId,
        calendarCreate,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * CalendarProfileApi - axios parameter creator
 */
export const CalendarProfileApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Add Profile Source
     * @param {string} profileId
     * @param {SourceCreate} sourceCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProfileSourceApiProfileProfileIdSourcePost: async (
      profileId: string,
      sourceCreate: SourceCreate,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "addProfileSourceApiProfileProfileIdSourcePost",
        "profileId",
        profileId,
      );
      // verify required parameter 'sourceCreate' is not null or undefined
      assertParamExists(
        "addProfileSourceApiProfileProfileIdSourcePost",
        "sourceCreate",
        sourceCreate,
      );
      const localVarPath = `/api/profile/{profile_id}/source`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        sourceCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create Profile
     * @param {ProfileCreate} profileCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProfileApiProfilePost: async (
      profileCreate: ProfileCreate,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileCreate' is not null or undefined
      assertParamExists(
        "createProfileApiProfilePost",
        "profileCreate",
        profileCreate,
      );
      const localVarPath = `/api/profile`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        profileCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Profile
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfileApiProfileProfileIdDelete: async (
      profileId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "deleteProfileApiProfileProfileIdDelete",
        "profileId",
        profileId,
      );
      const localVarPath = `/api/profile/{profile_id}`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Profile Source
     * @param {string} profileId
     * @param {string} sourceId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete: async (
      profileId: string,
      sourceId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete",
        "profileId",
        profileId,
      );
      // verify required parameter 'sourceId' is not null or undefined
      assertParamExists(
        "deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete",
        "sourceId",
        sourceId,
      );
      const localVarPath = `/api/profile/{profile_id}/source/{source_id}`
        .replace(`{${"profile_id"}}`, encodeURIComponent(String(profileId)))
        .replace(`{${"source_id"}}`, encodeURIComponent(String(sourceId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Profile
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProfileApiProfileProfileIdGet: async (
      profileId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "getProfileApiProfileProfileIdGet",
        "profileId",
        profileId,
      );
      const localVarPath = `/api/profile/{profile_id}`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List Profile Sync
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfileSyncApiProfileProfileIdSourceGet: async (
      profileId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "listProfileSyncApiProfileProfileIdSourceGet",
        "profileId",
        profileId,
      );
      const localVarPath = `/api/profile/{profile_id}/source`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List Profiles
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfilesApiProfileGet: async (
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/profile`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Trigger Profile Sync
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    triggerProfileSyncApiProfileProfileIdSyncPost: async (
      profileId: string,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "triggerProfileSyncApiProfileProfileIdSyncPost",
        "profileId",
        profileId,
      );
      const localVarPath = `/api/profile/{profile_id}/sync`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update Profile
     * @param {string} profileId
     * @param {ProfileCreate} profileCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProfileApiProfileProfileIdPut: async (
      profileId: string,
      profileCreate: ProfileCreate,
      authorization?: string | null,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists(
        "updateProfileApiProfileProfileIdPut",
        "profileId",
        profileId,
      );
      // verify required parameter 'profileCreate' is not null or undefined
      assertParamExists(
        "updateProfileApiProfileProfileIdPut",
        "profileCreate",
        profileCreate,
      );
      const localVarPath = `/api/profile/{profile_id}`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      if (authorization != null) {
        localVarHeaderParameter["authorization"] = String(authorization);
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        profileCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CalendarProfileApi - functional programming interface
 */
export const CalendarProfileApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    CalendarProfileApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Add Profile Source
     * @param {string} profileId
     * @param {SourceCreate} sourceCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addProfileSourceApiProfileProfileIdSourcePost(
      profileId: string,
      sourceCreate: SourceCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.addProfileSourceApiProfileProfileIdSourcePost(
          profileId,
          sourceCreate,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.addProfileSourceApiProfileProfileIdSourcePost"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Create Profile
     * @param {ProfileCreate} profileCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createProfileApiProfilePost(
      profileCreate: ProfileCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ProfileReadShort>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createProfileApiProfilePost(
          profileCreate,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.createProfileApiProfilePost"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete Profile
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteProfileApiProfileProfileIdDelete(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteProfileApiProfileProfileIdDelete(
          profileId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.deleteProfileApiProfileProfileIdDelete"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete Profile Source
     * @param {string} profileId
     * @param {string} sourceId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete(
      profileId: string,
      sourceId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete(
          profileId,
          sourceId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get Profile
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getProfileApiProfileProfileIdGet(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ProfileReadFull>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getProfileApiProfileProfileIdGet(
          profileId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.getProfileApiProfileProfileIdGet"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary List Profile Sync
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listProfileSyncApiProfileProfileIdSourceGet(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<SourceRead>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listProfileSyncApiProfileProfileIdSourceGet(
          profileId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.listProfileSyncApiProfileProfileIdSourceGet"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary List Profiles
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listProfilesApiProfileGet(
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<ProfileReadShort>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listProfilesApiProfileGet(
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.listProfilesApiProfileGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Trigger Profile Sync
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async triggerProfileSyncApiProfileProfileIdSyncPost(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.triggerProfileSyncApiProfileProfileIdSyncPost(
          profileId,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.triggerProfileSyncApiProfileProfileIdSyncPost"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update Profile
     * @param {string} profileId
     * @param {ProfileCreate} profileCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateProfileApiProfileProfileIdPut(
      profileId: string,
      profileCreate: ProfileCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ProfileReadShort>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateProfileApiProfileProfileIdPut(
          profileId,
          profileCreate,
          authorization,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap[
          "CalendarProfileApi.updateProfileApiProfileProfileIdPut"
        ]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CalendarProfileApi - factory interface
 */
export const CalendarProfileApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CalendarProfileApiFp(configuration);
  return {
    /**
     *
     * @summary Add Profile Source
     * @param {string} profileId
     * @param {SourceCreate} sourceCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProfileSourceApiProfileProfileIdSourcePost(
      profileId: string,
      sourceCreate: SourceCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .addProfileSourceApiProfileProfileIdSourcePost(
          profileId,
          sourceCreate,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create Profile
     * @param {ProfileCreate} profileCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProfileApiProfilePost(
      profileCreate: ProfileCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProfileReadShort> {
      return localVarFp
        .createProfileApiProfilePost(profileCreate, authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Profile
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfileApiProfileProfileIdDelete(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteProfileApiProfileProfileIdDelete(
          profileId,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Profile Source
     * @param {string} profileId
     * @param {string} sourceId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete(
      profileId: string,
      sourceId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete(
          profileId,
          sourceId,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Profile
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProfileApiProfileProfileIdGet(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProfileReadFull> {
      return localVarFp
        .getProfileApiProfileProfileIdGet(profileId, authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary List Profile Sync
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfileSyncApiProfileProfileIdSourceGet(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<SourceRead>> {
      return localVarFp
        .listProfileSyncApiProfileProfileIdSourceGet(
          profileId,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary List Profiles
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfilesApiProfileGet(
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<ProfileReadShort>> {
      return localVarFp
        .listProfilesApiProfileGet(authorization, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Trigger Profile Sync
     * @param {string} profileId
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    triggerProfileSyncApiProfileProfileIdSyncPost(
      profileId: string,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .triggerProfileSyncApiProfileProfileIdSyncPost(
          profileId,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update Profile
     * @param {string} profileId
     * @param {ProfileCreate} profileCreate
     * @param {string | null} [authorization]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProfileApiProfileProfileIdPut(
      profileId: string,
      profileCreate: ProfileCreate,
      authorization?: string | null,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ProfileReadShort> {
      return localVarFp
        .updateProfileApiProfileProfileIdPut(
          profileId,
          profileCreate,
          authorization,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CalendarProfileApi - object-oriented interface
 */
export class CalendarProfileApi extends BaseAPI {
  /**
   *
   * @summary Add Profile Source
   * @param {string} profileId
   * @param {SourceCreate} sourceCreate
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public addProfileSourceApiProfileProfileIdSourcePost(
    profileId: string,
    sourceCreate: SourceCreate,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .addProfileSourceApiProfileProfileIdSourcePost(
        profileId,
        sourceCreate,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create Profile
   * @param {ProfileCreate} profileCreate
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createProfileApiProfilePost(
    profileCreate: ProfileCreate,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .createProfileApiProfilePost(profileCreate, authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Profile
   * @param {string} profileId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteProfileApiProfileProfileIdDelete(
    profileId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .deleteProfileApiProfileProfileIdDelete(profileId, authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Profile Source
   * @param {string} profileId
   * @param {string} sourceId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete(
    profileId: string,
    sourceId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .deleteProfileSourceApiProfileProfileIdSourceSourceIdDelete(
        profileId,
        sourceId,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Profile
   * @param {string} profileId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getProfileApiProfileProfileIdGet(
    profileId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .getProfileApiProfileProfileIdGet(profileId, authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List Profile Sync
   * @param {string} profileId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listProfileSyncApiProfileProfileIdSourceGet(
    profileId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .listProfileSyncApiProfileProfileIdSourceGet(
        profileId,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List Profiles
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listProfilesApiProfileGet(
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .listProfilesApiProfileGet(authorization, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Trigger Profile Sync
   * @param {string} profileId
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public triggerProfileSyncApiProfileProfileIdSyncPost(
    profileId: string,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .triggerProfileSyncApiProfileProfileIdSyncPost(
        profileId,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update Profile
   * @param {string} profileId
   * @param {ProfileCreate} profileCreate
   * @param {string | null} [authorization]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateProfileApiProfileProfileIdPut(
    profileId: string,
    profileCreate: ProfileCreate,
    authorization?: string | null,
    options?: RawAxiosRequestConfig,
  ) {
    return CalendarProfileApiFp(this.configuration)
      .updateProfileApiProfileProfileIdPut(
        profileId,
        profileCreate,
        authorization,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthApiHealthGet: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/health`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async healthApiHealthGet(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.healthApiHealthGet(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["HealthApi.healthApiHealthGet"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = HealthApiFp(configuration);
  return {
    /**
     *
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthApiHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp
        .healthApiHealthGet(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
  /**
   *
   * @summary Health
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public healthApiHealthGet(options?: RawAxiosRequestConfig) {
    return HealthApiFp(this.configuration)
      .healthApiHealthGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
