/* tslint:disable */
/* eslint-disable */
/**
 * Chronicle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
  replaceWithSerializableTypeIfNeeded,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

export interface Action {
  id: number;
  rule_id: number;
  name: string;
  arguments: { [key: string]: any };
}
export interface CalendarCreate {
  type: string;
  url: string;
  username?: string | null;
  password?: string | null;
}
export interface CalendarRead {
  id: string;
  type: string;
  url: string;
  username: string | null;
  password: string | null;
}
export interface Condition {
  id: number;
  rule_id: number;
  field: string;
  operator: string;
  value: string;
}
export interface CreateTask {
  title: string;
  description?: string | null;
  due_date?: string | null;
  duration?: number;
  not_before?: string | null;
  priority?: number;
  profile_id?: string | null;
}
export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}
export interface LocationInner {}
export interface LoginRequest {
  email: string;
  password: string;
}
export interface ProfileCreate {
  name: string;
  main_calendar_id: string;
}
export interface ProfileReadFull {
  id: string;
  name: string;
  main_calendar_id: string | null;
  main_calendar: CalendarRead | null;
  rules?: Array<Rule>;
}
export interface ProfileReadShort {
  id: string;
  name: string;
  main_calendar_id: string | null;
}
export interface RegisterRequest {
  email: string;
  password: string;
}
export interface Rule {
  id: number;
  source_id: string;
  enabled: boolean;
  name: string;
  conditions?: Array<Condition>;
  actions?: Array<Action>;
}
export interface SourceCreate {
  calendar_id: string;
}
export interface SourceRead {
  id: string;
  calendar_id: string;
  calendar: CalendarRead;
}
export interface Task {
  id: string;
  completed: boolean;
  title: string;
  description: string;
  due_date?: string | null;
  duration?: number;
  not_before?: string | null;
  priority?: number;
  profile?: ProfileReadShort | null;
}
export interface TokenResponse {
  access_token: string;
  token_type?: string;
}
export interface UpdateTask {
  title?: string | null;
  description?: string | null;
  due_date?: string | null;
  duration?: number | null;
  not_before?: string | null;
  priority?: number | null;
  profile_id?: string | null;
  completed?: boolean | null;
}
export interface ValidationError {
  loc: Array<LocationInner>;
  msg: string;
  type: string;
  input?: any;
  ctx?: object;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Get Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getToken: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/token`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Login
     * @param {LoginRequest} loginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login: async (
      loginRequest: LoginRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'loginRequest' is not null or undefined
      assertParamExists("login", "loginRequest", loginRequest);
      const localVarPath = `/api/auth/login`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        loginRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logout: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/logout`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    me: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/auth/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Register
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    register: async (
      registerRequest: RegisterRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'registerRequest' is not null or undefined
      assertParamExists("register", "registerRequest", registerRequest);
      const localVarPath = `/api/auth/register`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        registerRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Get Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getToken(
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getToken(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.getToken"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Login
     * @param {LoginRequest} loginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async login(
      loginRequest: LoginRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.login(
        loginRequest,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.login"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async logout(
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.logout"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async me(
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.me(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.me"]?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Register
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async register(
      registerRequest: RegisterRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.register(
        registerRequest,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["AuthApi.register"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = AuthApiFp(configuration);
  return {
    /**
     *
     * @summary Get Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getToken(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp
        .getToken(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Login
     * @param {LoginRequest} loginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login(
      loginRequest: LoginRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<TokenResponse> {
      return localVarFp
        .login(loginRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logout(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp
        .logout(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    me(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp.me(options).then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Register
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    register(
      registerRequest: RegisterRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<TokenResponse> {
      return localVarFp
        .register(registerRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
  /**
   *
   * @summary Get Token
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getToken(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .getToken(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Login
   * @param {LoginRequest} loginRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .login(loginRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Logout
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public logout(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .logout(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Me
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public me(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .me(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Register
   * @param {RegisterRequest} registerRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public register(
    registerRequest: RegisterRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AuthApiFp(this.configuration)
      .register(registerRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * CalendarApi - axios parameter creator
 */
export const CalendarApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Create a new calendar for the current user.
     * @summary Create Calendar
     * @param {CalendarCreate} calendarCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCalendar: async (
      calendarCreate: CalendarCreate,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarCreate' is not null or undefined
      assertParamExists("createCalendar", "calendarCreate", calendarCreate);
      const localVarPath = `/api/calendar`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        calendarCreate,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete a calendar by ID.
     * @summary Delete Calendar
     * @param {string} calendarId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCalendar: async (
      calendarId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarId' is not null or undefined
      assertParamExists("deleteCalendar", "calendarId", calendarId);
      const localVarPath = `/api/calendar/{calendar_id}`.replace(
        `{${"calendar_id"}}`,
        encodeURIComponent(String(calendarId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieve a calendar by ID.
     * @summary Get Calendar
     * @param {string} calendarId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCalendar: async (
      calendarId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarId' is not null or undefined
      assertParamExists("getCalendar", "calendarId", calendarId);
      const localVarPath = `/api/calendar/{calendar_id}`.replace(
        `{${"calendar_id"}}`,
        encodeURIComponent(String(calendarId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieve all calendars for the current user.
     * @summary List Calendars
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCalendars: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/calendar`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Update a calendar by ID.
     * @summary Update Calendar
     * @param {string} calendarId
     * @param {CalendarCreate} calendarCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCalendar: async (
      calendarId: string,
      calendarCreate: CalendarCreate,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'calendarId' is not null or undefined
      assertParamExists("updateCalendar", "calendarId", calendarId);
      // verify required parameter 'calendarCreate' is not null or undefined
      assertParamExists("updateCalendar", "calendarCreate", calendarCreate);
      const localVarPath = `/api/calendar/{calendar_id}`.replace(
        `{${"calendar_id"}}`,
        encodeURIComponent(String(calendarId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        calendarCreate,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CalendarApi - functional programming interface
 */
export const CalendarApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CalendarApiAxiosParamCreator(configuration);
  return {
    /**
     * Create a new calendar for the current user.
     * @summary Create Calendar
     * @param {CalendarCreate} calendarCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createCalendar(
      calendarCreate: CalendarCreate,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalendarRead>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createCalendar(
        calendarCreate,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.createCalendar"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Delete a calendar by ID.
     * @summary Delete Calendar
     * @param {string} calendarId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteCalendar(
      calendarId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCalendar(
        calendarId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.deleteCalendar"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieve a calendar by ID.
     * @summary Get Calendar
     * @param {string} calendarId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCalendar(
      calendarId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalendarRead>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getCalendar(
        calendarId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.getCalendar"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieve all calendars for the current user.
     * @summary List Calendars
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listCalendars(
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<CalendarRead>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listCalendars(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.listCalendars"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Update a calendar by ID.
     * @summary Update Calendar
     * @param {string} calendarId
     * @param {CalendarCreate} calendarCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateCalendar(
      calendarId: string,
      calendarCreate: CalendarCreate,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalendarRead>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateCalendar(
        calendarId,
        calendarCreate,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarApi.updateCalendar"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CalendarApi - factory interface
 */
export const CalendarApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = CalendarApiFp(configuration);
  return {
    /**
     * Create a new calendar for the current user.
     * @summary Create Calendar
     * @param {CalendarCreate} calendarCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCalendar(
      calendarCreate: CalendarCreate,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CalendarRead> {
      return localVarFp
        .createCalendar(calendarCreate, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete a calendar by ID.
     * @summary Delete Calendar
     * @param {string} calendarId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCalendar(
      calendarId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .deleteCalendar(calendarId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieve a calendar by ID.
     * @summary Get Calendar
     * @param {string} calendarId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCalendar(
      calendarId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CalendarRead> {
      return localVarFp
        .getCalendar(calendarId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieve all calendars for the current user.
     * @summary List Calendars
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCalendars(
      options?: RawAxiosRequestConfig
    ): AxiosPromise<Array<CalendarRead>> {
      return localVarFp
        .listCalendars(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Update a calendar by ID.
     * @summary Update Calendar
     * @param {string} calendarId
     * @param {CalendarCreate} calendarCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCalendar(
      calendarId: string,
      calendarCreate: CalendarCreate,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CalendarRead> {
      return localVarFp
        .updateCalendar(calendarId, calendarCreate, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CalendarApi - object-oriented interface
 */
export class CalendarApi extends BaseAPI {
  /**
   * Create a new calendar for the current user.
   * @summary Create Calendar
   * @param {CalendarCreate} calendarCreate
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createCalendar(
    calendarCreate: CalendarCreate,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarApiFp(this.configuration)
      .createCalendar(calendarCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete a calendar by ID.
   * @summary Delete Calendar
   * @param {string} calendarId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteCalendar(calendarId: string, options?: RawAxiosRequestConfig) {
    return CalendarApiFp(this.configuration)
      .deleteCalendar(calendarId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieve a calendar by ID.
   * @summary Get Calendar
   * @param {string} calendarId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getCalendar(calendarId: string, options?: RawAxiosRequestConfig) {
    return CalendarApiFp(this.configuration)
      .getCalendar(calendarId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieve all calendars for the current user.
   * @summary List Calendars
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listCalendars(options?: RawAxiosRequestConfig) {
    return CalendarApiFp(this.configuration)
      .listCalendars(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Update a calendar by ID.
   * @summary Update Calendar
   * @param {string} calendarId
   * @param {CalendarCreate} calendarCreate
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateCalendar(
    calendarId: string,
    calendarCreate: CalendarCreate,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarApiFp(this.configuration)
      .updateCalendar(calendarId, calendarCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * CalendarProfileApi - axios parameter creator
 */
export const CalendarProfileApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Add Profile Source
     * @param {string} profileId
     * @param {SourceCreate} sourceCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProfileSource: async (
      profileId: string,
      sourceCreate: SourceCreate,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("addProfileSource", "profileId", profileId);
      // verify required parameter 'sourceCreate' is not null or undefined
      assertParamExists("addProfileSource", "sourceCreate", sourceCreate);
      const localVarPath = `/api/profile/{profile_id}/source`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        sourceCreate,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create Profile
     * @param {ProfileCreate} profileCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProfile: async (
      profileCreate: ProfileCreate,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileCreate' is not null or undefined
      assertParamExists("createProfile", "profileCreate", profileCreate);
      const localVarPath = `/api/profile`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        profileCreate,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Profile
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfile: async (
      profileId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("deleteProfile", "profileId", profileId);
      const localVarPath = `/api/profile/{profile_id}`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete Profile Source
     * @param {string} profileId
     * @param {string} sourceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfileSource: async (
      profileId: string,
      sourceId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("deleteProfileSource", "profileId", profileId);
      // verify required parameter 'sourceId' is not null or undefined
      assertParamExists("deleteProfileSource", "sourceId", sourceId);
      const localVarPath = `/api/profile/{profile_id}/source/{source_id}`
        .replace(`{${"profile_id"}}`, encodeURIComponent(String(profileId)))
        .replace(`{${"source_id"}}`, encodeURIComponent(String(sourceId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Profile
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProfile: async (
      profileId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("getProfile", "profileId", profileId);
      const localVarPath = `/api/profile/{profile_id}`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List Profile Sync
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfileSources: async (
      profileId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("listProfileSources", "profileId", profileId);
      const localVarPath = `/api/profile/{profile_id}/source`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary List Profiles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfiles: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/profile`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Trigger Profile Sync
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    triggerProfileSync: async (
      profileId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("triggerProfileSync", "profileId", profileId);
      const localVarPath = `/api/profile/{profile_id}/sync`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update Profile
     * @param {string} profileId
     * @param {ProfileCreate} profileCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProfile: async (
      profileId: string,
      profileCreate: ProfileCreate,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'profileId' is not null or undefined
      assertParamExists("updateProfile", "profileId", profileId);
      // verify required parameter 'profileCreate' is not null or undefined
      assertParamExists("updateProfile", "profileCreate", profileCreate);
      const localVarPath = `/api/profile/{profile_id}`.replace(
        `{${"profile_id"}}`,
        encodeURIComponent(String(profileId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        profileCreate,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CalendarProfileApi - functional programming interface
 */
export const CalendarProfileApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    CalendarProfileApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Add Profile Source
     * @param {string} profileId
     * @param {SourceCreate} sourceCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addProfileSource(
      profileId: string,
      sourceCreate: SourceCreate,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.addProfileSource(
          profileId,
          sourceCreate,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.addProfileSource"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Create Profile
     * @param {ProfileCreate} profileCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createProfile(
      profileCreate: ProfileCreate,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<ProfileReadShort>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createProfile(
        profileCreate,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.createProfile"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete Profile
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteProfile(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProfile(
        profileId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.deleteProfile"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete Profile Source
     * @param {string} profileId
     * @param {string} sourceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteProfileSource(
      profileId: string,
      sourceId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteProfileSource(
          profileId,
          sourceId,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.deleteProfileSource"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Get Profile
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getProfile(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<ProfileReadFull>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getProfile(
        profileId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.getProfile"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary List Profile Sync
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listProfileSources(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<SourceRead>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listProfileSources(profileId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.listProfileSources"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary List Profiles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listProfiles(
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<ProfileReadShort>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listProfiles(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.listProfiles"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Trigger Profile Sync
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async triggerProfileSync(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.triggerProfileSync(profileId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.triggerProfileSync"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update Profile
     * @param {string} profileId
     * @param {ProfileCreate} profileCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateProfile(
      profileId: string,
      profileCreate: ProfileCreate,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<ProfileReadShort>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateProfile(
        profileId,
        profileCreate,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["CalendarProfileApi.updateProfile"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * CalendarProfileApi - factory interface
 */
export const CalendarProfileApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = CalendarProfileApiFp(configuration);
  return {
    /**
     *
     * @summary Add Profile Source
     * @param {string} profileId
     * @param {SourceCreate} sourceCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProfileSource(
      profileId: string,
      sourceCreate: SourceCreate,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<any> {
      return localVarFp
        .addProfileSource(profileId, sourceCreate, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create Profile
     * @param {ProfileCreate} profileCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProfile(
      profileCreate: ProfileCreate,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ProfileReadShort> {
      return localVarFp
        .createProfile(profileCreate, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Profile
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfile(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .deleteProfile(profileId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete Profile Source
     * @param {string} profileId
     * @param {string} sourceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProfileSource(
      profileId: string,
      sourceId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .deleteProfileSource(profileId, sourceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Profile
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProfile(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ProfileReadFull> {
      return localVarFp
        .getProfile(profileId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary List Profile Sync
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfileSources(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<Array<SourceRead>> {
      return localVarFp
        .listProfileSources(profileId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary List Profiles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listProfiles(
      options?: RawAxiosRequestConfig
    ): AxiosPromise<Array<ProfileReadShort>> {
      return localVarFp
        .listProfiles(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Trigger Profile Sync
     * @param {string} profileId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    triggerProfileSync(
      profileId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<any> {
      return localVarFp
        .triggerProfileSync(profileId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update Profile
     * @param {string} profileId
     * @param {ProfileCreate} profileCreate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProfile(
      profileId: string,
      profileCreate: ProfileCreate,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ProfileReadShort> {
      return localVarFp
        .updateProfile(profileId, profileCreate, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CalendarProfileApi - object-oriented interface
 */
export class CalendarProfileApi extends BaseAPI {
  /**
   *
   * @summary Add Profile Source
   * @param {string} profileId
   * @param {SourceCreate} sourceCreate
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public addProfileSource(
    profileId: string,
    sourceCreate: SourceCreate,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarProfileApiFp(this.configuration)
      .addProfileSource(profileId, sourceCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create Profile
   * @param {ProfileCreate} profileCreate
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createProfile(
    profileCreate: ProfileCreate,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarProfileApiFp(this.configuration)
      .createProfile(profileCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Profile
   * @param {string} profileId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteProfile(profileId: string, options?: RawAxiosRequestConfig) {
    return CalendarProfileApiFp(this.configuration)
      .deleteProfile(profileId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete Profile Source
   * @param {string} profileId
   * @param {string} sourceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteProfileSource(
    profileId: string,
    sourceId: string,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarProfileApiFp(this.configuration)
      .deleteProfileSource(profileId, sourceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Profile
   * @param {string} profileId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getProfile(profileId: string, options?: RawAxiosRequestConfig) {
    return CalendarProfileApiFp(this.configuration)
      .getProfile(profileId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List Profile Sync
   * @param {string} profileId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listProfileSources(
    profileId: string,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarProfileApiFp(this.configuration)
      .listProfileSources(profileId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary List Profiles
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listProfiles(options?: RawAxiosRequestConfig) {
    return CalendarProfileApiFp(this.configuration)
      .listProfiles(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Trigger Profile Sync
   * @param {string} profileId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public triggerProfileSync(
    profileId: string,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarProfileApiFp(this.configuration)
      .triggerProfileSync(profileId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update Profile
   * @param {string} profileId
   * @param {ProfileCreate} profileCreate
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateProfile(
    profileId: string,
    profileCreate: ProfileCreate,
    options?: RawAxiosRequestConfig
  ) {
    return CalendarProfileApiFp(this.configuration)
      .updateProfile(profileId, profileCreate, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    health: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/health`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async health(
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.health(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["HealthApi.health"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = HealthApiFp(configuration);
  return {
    /**
     *
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    health(options?: RawAxiosRequestConfig): AxiosPromise<any> {
      return localVarFp
        .health(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
  /**
   *
   * @summary Health
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public health(options?: RawAxiosRequestConfig) {
    return HealthApiFp(this.configuration)
      .health(options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * TaskApi - axios parameter creator
 */
export const TaskApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Create a new task for the current user.
     * @summary Create Task
     * @param {CreateTask} createTask
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTask: async (
      createTask: CreateTask,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'createTask' is not null or undefined
      assertParamExists("createTask", "createTask", createTask);
      const localVarPath = `/api/task`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createTask,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete a task by ID.
     * @summary Delete Task
     * @param {string} taskId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTask: async (
      taskId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'taskId' is not null or undefined
      assertParamExists("deleteTask", "taskId", taskId);
      const localVarPath = `/api/task/{task_id}`.replace(
        `{${"task_id"}}`,
        encodeURIComponent(String(taskId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieve a task by ID.
     * @summary Get Task
     * @param {string} taskId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTask: async (
      taskId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'taskId' is not null or undefined
      assertParamExists("getTask", "taskId", taskId);
      const localVarPath = `/api/task/{task_id}`.replace(
        `{${"task_id"}}`,
        encodeURIComponent(String(taskId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Retrieve all tasks for the current user.
     * @summary List Tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTasks: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/task`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Update a task by ID.
     * @summary Update Task
     * @param {string} taskId
     * @param {UpdateTask} updateTask
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTask: async (
      taskId: string,
      updateTask: UpdateTask,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'taskId' is not null or undefined
      assertParamExists("updateTask", "taskId", taskId);
      // verify required parameter 'updateTask' is not null or undefined
      assertParamExists("updateTask", "updateTask", updateTask);
      const localVarPath = `/api/task/{task_id}`.replace(
        `{${"task_id"}}`,
        encodeURIComponent(String(taskId))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";
      localVarHeaderParameter["Accept"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateTask,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TaskApi - functional programming interface
 */
export const TaskApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TaskApiAxiosParamCreator(configuration);
  return {
    /**
     * Create a new task for the current user.
     * @summary Create Task
     * @param {CreateTask} createTask
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createTask(
      createTask: CreateTask,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createTask(
        createTask,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaskApi.createTask"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Delete a task by ID.
     * @summary Delete Task
     * @param {string} taskId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTask(
      taskId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTask(
        taskId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaskApi.deleteTask"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieve a task by ID.
     * @summary Get Task
     * @param {string} taskId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTask(
      taskId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTask(
        taskId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaskApi.getTask"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Retrieve all tasks for the current user.
     * @summary List Tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listTasks(
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Task>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listTasks(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaskApi.listTasks"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Update a task by ID.
     * @summary Update Task
     * @param {string} taskId
     * @param {UpdateTask} updateTask
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateTask(
      taskId: string,
      updateTask: UpdateTask,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Task>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateTask(
        taskId,
        updateTask,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["TaskApi.updateTask"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * TaskApi - factory interface
 */
export const TaskApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = TaskApiFp(configuration);
  return {
    /**
     * Create a new task for the current user.
     * @summary Create Task
     * @param {CreateTask} createTask
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTask(
      createTask: CreateTask,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<Task> {
      return localVarFp
        .createTask(createTask, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete a task by ID.
     * @summary Delete Task
     * @param {string} taskId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTask(
      taskId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .deleteTask(taskId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieve a task by ID.
     * @summary Get Task
     * @param {string} taskId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTask(
      taskId: string,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<Task> {
      return localVarFp
        .getTask(taskId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Retrieve all tasks for the current user.
     * @summary List Tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTasks(options?: RawAxiosRequestConfig): AxiosPromise<Array<Task>> {
      return localVarFp
        .listTasks(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Update a task by ID.
     * @summary Update Task
     * @param {string} taskId
     * @param {UpdateTask} updateTask
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTask(
      taskId: string,
      updateTask: UpdateTask,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<Task> {
      return localVarFp
        .updateTask(taskId, updateTask, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * TaskApi - object-oriented interface
 */
export class TaskApi extends BaseAPI {
  /**
   * Create a new task for the current user.
   * @summary Create Task
   * @param {CreateTask} createTask
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createTask(createTask: CreateTask, options?: RawAxiosRequestConfig) {
    return TaskApiFp(this.configuration)
      .createTask(createTask, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete a task by ID.
   * @summary Delete Task
   * @param {string} taskId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteTask(taskId: string, options?: RawAxiosRequestConfig) {
    return TaskApiFp(this.configuration)
      .deleteTask(taskId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieve a task by ID.
   * @summary Get Task
   * @param {string} taskId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTask(taskId: string, options?: RawAxiosRequestConfig) {
    return TaskApiFp(this.configuration)
      .getTask(taskId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Retrieve all tasks for the current user.
   * @summary List Tasks
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public listTasks(options?: RawAxiosRequestConfig) {
    return TaskApiFp(this.configuration)
      .listTasks(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Update a task by ID.
   * @summary Update Task
   * @param {string} taskId
   * @param {UpdateTask} updateTask
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public updateTask(
    taskId: string,
    updateTask: UpdateTask,
    options?: RawAxiosRequestConfig
  ) {
    return TaskApiFp(this.configuration)
      .updateTask(taskId, updateTask, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
