name: General CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:

  yaml-lint:
    name: Check YAML format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate YAML files
        run: find . -name "*.yaml" -o -name "*.yml" | xargs yamllint

  trufflehog-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.93.0
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --debug --only-verified
