name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_PRIVATE_KEY }}
          installation-id: ${{ secrets.RELEASE_PLEASE_INSTALLATION_ID }}
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: chronicle
          monorepo-tags: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          token: ${{ steps.app-token.outputs.token }}
          extra-files: ["services/worker/pyproject.yaml", "services/backend/pyproject.yaml"]
